"""Add code and rate columns to currencies

Revision ID: 4a4aff4b9bd8
Revises: 05b74c7e9820
Create Date: 2025-01-01 12:01:26.510382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision: str = '4a4aff4b9bd8'
down_revision: Union[str, None] = '05b74c7e9820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CURRENCIES',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('input', sa.Float(), nullable=True),
    sa.Column('output', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_CURRENCIES_id'), 'CURRENCIES', ['id'], unique=False)
    op.create_table('CUSTOMER',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('identite', sa.Unicode(length=255), nullable=True),
    sa.Column('telephone', sa.Unicode(length=20), nullable=True),
    sa.Column('date_naisse', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CUSTOMER_id'), 'CUSTOMER', ['id'], unique=False)
    op.create_table('EMPLOYEE',
    sa.Column('employee_id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('carte_ident', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('date_naiss', sa.Date(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('permission_role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index(op.f('ix_EMPLOYEE_employee_id'), 'EMPLOYEE', ['employee_id'], unique=False)
    op.create_table('TREASURY_OPERATIONS',
    sa.Column('treasury_operations_id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('input', sa.Float(), nullable=True),
    sa.Column('output', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('treasury_operations_id')
    )
    op.create_index(op.f('ix_TREASURY_OPERATIONS_treasury_operations_id'), 'TREASURY_OPERATIONS', ['treasury_operations_id'], unique=False)
    op.create_table('DEBTS',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('debt_date', sa.Date(), nullable=False),
    sa.Column('paid_debt', sa.Float(), nullable=True),
    sa.Column('current_debt', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['CUSTOMER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DEBTS_id'), 'DEBTS', ['id'], unique=False)
    op.create_table('DEPOSITS',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('person_name', sa.Unicode(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('deposit_date', sa.Date(), nullable=False),
    sa.Column('released_deposit', sa.Float(), nullable=True),
    sa.Column('current_debt', sa.Float(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['CUSTOMER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_DEPOSITS_id'), 'DEPOSITS', ['id'], unique=False)
    op.drop_table('deposits')
    op.drop_table('customer')
    op.drop_table('employee')
    op.drop_table('debts')
    op.drop_table('currencies')
    op.drop_table('treasury_operations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treasury_operations',
    sa.Column('treasury_operations_id', sa.INTEGER(), sa.Identity(always=False, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('input', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('output', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('balance', sa.DOUBLE_PRECISION(), nullable=True),
    sa.PrimaryKeyConstraint('treasury_operations_id', name='sys_c008293')
    )
    op.create_table('currencies',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('input', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('output', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('balance', sa.DOUBLE_PRECISION(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='sys_c008282')
    )
    op.create_table('debts',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('debt_date', oracle.DATE(), nullable=False),
    sa.Column('paid_debt', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('current_debt', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', oracle.DATE(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_at', oracle.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='sys_c008299'),
    sa.PrimaryKeyConstraint('id', name='sys_c008298')
    )
    op.create_table('employee',
    sa.Column('employee_id', sa.INTEGER(), sa.Identity(always=False, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('carte_ident', sa.VARCHAR(length=255), nullable=True),
    sa.Column('telephone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('date_naiss', oracle.DATE(), nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('permission_role', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('employee_id', name='sys_c008290')
    )
    op.create_table('customer',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('identite', sa.VARCHAR(length=255), nullable=True),
    sa.Column('telephone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('date_naisse', oracle.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='sys_c008285'),
    oracle_resolve_synonyms=False
    )
    op.create_table('deposits',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, on_null=False, start=1, increment=1, minvalue=1, maxvalue=9999999999999999999999999999, cycle=False, cache=20, order=False), nullable=False),
    sa.Column('person_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('deposit_date', oracle.DATE(), nullable=False),
    sa.Column('released_deposit', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('current_debt', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='sys_c008305'),
    sa.PrimaryKeyConstraint('id', name='sys_c008304')
    )
    op.drop_index(op.f('ix_DEPOSITS_id'), table_name='DEPOSITS')
    op.drop_table('DEPOSITS')
    op.drop_index(op.f('ix_DEBTS_id'), table_name='DEBTS')
    op.drop_table('DEBTS')
    op.drop_index(op.f('ix_TREASURY_OPERATIONS_treasury_operations_id'), table_name='TREASURY_OPERATIONS')
    op.drop_table('TREASURY_OPERATIONS')
    op.drop_index(op.f('ix_EMPLOYEE_employee_id'), table_name='EMPLOYEE')
    op.drop_table('EMPLOYEE')
    op.drop_index(op.f('ix_CUSTOMER_id'), table_name='CUSTOMER')
    op.drop_table('CUSTOMER')
    op.drop_index(op.f('ix_CURRENCIES_id'), table_name='CURRENCIES')
    op.drop_table('CURRENCIES')
    # ### end Alembic commands ###
